#!/usr/bin/env node

var TSC = require('path').resolve(__dirname, 'node_modules/typescript/bin/tsc.js');

eval(require('fs')
  .readFileSync(TSC, 'utf8')
  .replace(/batch\.batchCompile\(\);\s*$/, '')
  .replace(/\btsc\b/g, 'tscc'));

eval(require('fs').readFileSync(require('path').resolve(__dirname, 'emitter.js'), 'utf8'));
eval(require('fs').readFileSync(require('path').resolve(__dirname, 'patches.js'), 'utf8'));

process.mainModule.filename = TSC;
batch.batchCompile();
